/**
 * pnpm enrich:twitter [-- --dry-run] [-- --refresh-metrics]
 *
 * NOTE (B18): post readings live in `post.observations`, an append-only
 * history. This script does not write them today; when `--refresh-metrics`
 * is implemented (B12) it appends one observation with `source: "api"`
 * rather than overwriting the previous reading.
 *
 * One-time / occasional maintenance tool (docs/ENGINEERING.md §12). Never called
 * during `next build`, rendering, or CI.
 *
 * Fetches public tweet data for the posts already in `data/posts.json` and the
 * amplification evidence URLs in `data/amplifications.json` via the X API v2
 * tweet-lookup endpoint, then:
 *
 *  - posts: fills in `title` / `subject` / `summary` / `tags` for records the
 *    maintainer has curated in POST_ENRICHMENTS below (docs/DATA.md §5,
 *    docs/EDITORIAL.md §5 — this copy is authored by a human reading the fetched
 *    tweet text, never generated by this script), corrects `published_at` only
 *    if the API's `created_at` contradicts the stored date, and clears the
 *    `"Post content/title enrichment pending."` notes marker on records it
 *    successfully enriches.
 *  - amplifications: derives `action` and `related_post_id` directly from the
 *    API's `referenced_tweets` field (quoted -> quote_post, replied_to -> reply,
 *    retweeted -> repost) and confirms `entity_name` / `account` / `date`
 *    against the fetched tweet. Never promotes `status`.
 *
 * Never invents content: a post whose meaning depends on an image or quoted
 * tweet this tool cannot see is left untouched and flagged (see FLAGGED_POSTS).
 * A tweet the API cannot return (deleted/protected/not found) is flagged, never
 * guessed.
 *
 * Credentials: `X_BEARER_TOKEN` is read from `.env.local` and is never logged,
 * echoed, or written anywhere, including in error output.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";

import { postSchema, postsFileSchema, type Post } from "../src/schemas/post.schema";
import {
  amplificationSchema,
  amplificationsFileSchema,
  type Amplification,
} from "../src/schemas/amplification.schema";

const ROOT = process.cwd();
const DATA_DIR = resolve(ROOT, "data");
const CACHE_DIR = resolve(ROOT, ".cache");
const CACHE_FILE = resolve(CACHE_DIR, "twitter-enrichment.json");
const X_API_URL = "https://api.x.com/2/tweets";
const TWEET_FIELDS = "created_at,text,public_metrics,referenced_tweets,entities,note_tweet";
const EXPANSIONS = "author_id,referenced_tweets.id";
const USER_FIELDS = "username,name";
const MAX_RETRIES = 4;

// ---------------------------------------------------------------------------
// CLI args
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const isDryRun = args.includes("--dry-run");
const refreshMetrics = args.includes("--refresh-metrics");

// ---------------------------------------------------------------------------
// Stage B — human-authored post copy (docs/WORKPLAN.md B7, docs/ENGINEERING.md §12)
//
// Written by reading each post's fetched tweet text (full text via `note_tweet`
// where the tweet was longer than the classic 280-character view). Never
// generated mechanically. A post is only listed here when its own text is
// sufficient to describe it neutrally without seeing an attached image.
// ---------------------------------------------------------------------------

interface PostEnrichment {
  title: string;
  subject: string;
  summary: string;
  tags: string[];
}

const POST_ENRICHMENTS: Record<string, PostEnrichment> = {
  "post-layoffai-2098762091423203710": {
    title: "Trine University international enrollment records",
    subject: "Trine University",
    summary:
      "The post says Trine University's federal enrollment records list 9,123 graduate students, 98.3% of them foreign nationals, and describes payments to an overseas recruiting agency not reflected in the university's audited financial statements.",
    tags: ["higher education", "international students", "Trine University"],
  },
  "post-layoffai-2087170419027526094": {
    title: "Fastest-growing H-1B districts represented by Texas Republicans",
    subject: "H-1B visas by congressional district",
    summary:
      "The post says the eight U.S. congressional districts with the fastest-growing H-1B visa filings are all represented by Texas Republicans.",
    tags: ["H-1B", "Texas", "congressional districts"],
  },
  "post-layoffai-2038753137377325342": {
    title: "Meta ties promotions to AI adoption after layoffs",
    subject: "Meta layoffs and AI mandates",
    summary:
      "Following layoffs of about 700 employees and plans for 15,000 more, the post describes leaked internal Meta documents requiring large shares of code to be AI-assisted and factoring AI adoption into performance reviews.",
    tags: ["Meta", "AI adoption", "layoffs"],
  },
  "post-layoffai-2055002525519294970": {
    title: "Meta 2026 layoff total revised to 22,000",
    subject: "Meta layoffs",
    summary:
      "The post says Meta's 2026 job cuts total roughly 22,000 once unannounced reductions and cancelled openings are included, citing Reuters reporting alongside Meta's H-1B and green-card filing activity.",
    tags: ["Meta", "layoffs", "H-1B"],
  },
  "post-layoffai-2057485600346005923": {
    title: "Cloudflare CEO explains AI-driven layoffs",
    subject: "Cloudflare layoffs",
    summary:
      "The post describes Cloudflare laying off 1,100 employees during a record-revenue quarter and cites the CEO's Wall Street Journal op-ed on using AI to replace certain roles.",
    tags: ["Cloudflare", "AI", "layoffs"],
  },
  "post-layoffai-2051709389476946089": {
    title: "Cognizant layoff estimate revised to 15,000",
    subject: "Cognizant layoffs",
    summary:
      "The post says analysts revised Cognizant's layoff estimate from 4,000 to 15,000 employees, describing the company as a major H-1B employer.",
    tags: ["Cognizant", "layoffs", "H-1B"],
  },
  "post-layoffai-2065598432652472605": {
    title: "Wired report on internal turmoil at Meta",
    subject: "Meta AI restructuring",
    summary:
      "The post cites a Wired report describing internal turmoil at Meta following AI-related restructuring, including reassigned employees and a petition against workplace monitoring used to generate AI training data.",
    tags: ["Meta", "AI", "internal culture"],
  },
  "post-layoffai-2039080883270156557": {
    title: "Oracle layoffs amid Stargate data center buildout",
    subject: "Oracle layoffs",
    summary:
      "The post links Oracle's termination of about 30,000 employees to its data-center lease commitments and AI infrastructure spending tied to the Stargate project, contrasting the cuts with previously announced construction jobs.",
    tags: ["Oracle", "Stargate", "layoffs"],
  },
  "post-layoffai-2047314552191119792": {
    title: "LayoffHedge launches H-1B visa filing explorer",
    subject: "H-1B visa data tool",
    summary:
      "The post announces an interactive tool mapping H-1B visa filings by county across 11 fiscal years, cross-referenced against the account's layoff tracker.",
    tags: ["H-1B", "data tool", "immigration"],
  },
  "post-layoffai-2056858309618282743": {
    title: "Leaked audio on Meta employee monitoring for AI training",
    subject: "Meta AI training practices",
    summary:
      "The post describes leaked audio in which Meta's CEO reportedly discusses tracking employee device use to generate AI training data ahead of layoffs, saying employee-generated data outperforms outside contractors.",
    tags: ["Meta", "AI training", "employee monitoring"],
  },
};

/** Posts intentionally left un-enriched even though flagged pending — never guess. */
const FLAGGED_POSTS: Record<string, string> = {
  "post-layoffai-2099180586858393814":
    "Tweet text is only \"55 years of inflation\" attached to a photo (a chart) this tool cannot see. " +
    "The subject cannot be determined from text alone without guessing what the chart shows. Left untouched.",
};

// ---------------------------------------------------------------------------
// Env / credentials
// ---------------------------------------------------------------------------

/** Reads X_BEARER_TOKEN from .env.local without ever logging it. Never uses dotenv/`cat`. */
function loadBearerToken(): string {
  const envPath = resolve(ROOT, ".env.local");
  if (!existsSync(envPath)) {
    console.error(".env.local not found. Create it from .env.example and set X_BEARER_TOKEN.");
    process.exit(1);
  }
  const raw = readFileSync(envPath, "utf-8");
  for (const line of raw.split(/\r?\n/)) {
    const match = line.match(/^X_BEARER_TOKEN=(.*)$/);
    if (match) {
      const token = match[1]?.trim() ?? "";
      if (token.length === 0) break;
      return token;
    }
  }
  console.error("X_BEARER_TOKEN is missing or empty in .env.local.");
  process.exit(1);
}

// ---------------------------------------------------------------------------
// X API types (only the fields this script reads)
// ---------------------------------------------------------------------------

interface ReferencedTweet {
  type: "quoted" | "replied_to" | "retweeted";
  id: string;
}

interface ApiTweet {
  id: string;
  author_id?: string;
  created_at?: string;
  text: string;
  note_tweet?: { text: string };
  referenced_tweets?: ReferencedTweet[];
}

interface ApiUser {
  id: string;
  username: string;
  name: string;
}

interface ApiError {
  value?: string;
  detail?: string;
  title?: string;
}

interface TweetLookupResponse {
  data?: ApiTweet[];
  includes?: { users?: ApiUser[] };
  errors?: ApiError[];
}

// ---------------------------------------------------------------------------
// Fetch helpers
// ---------------------------------------------------------------------------

function extractStatusId(url: string): string | null {
  const match = url.match(/status\/(\d+)/);
  return match ? (match[1] ?? null) : null;
}

function chunk<T>(items: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let i = 0; i < items.length; i += size) chunks.push(items.slice(i, i + size));
  return chunks;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolvePromise) => setTimeout(resolvePromise, ms));
}

/**
 * Fetches one batch (<=100 ids) of tweets. Retries only on 429/5xx, respecting
 * `x-rate-limit-reset` / `retry-after` headers. Any other non-2xx status
 * (notably 401/403 — the Free X API tier does not permit tweet lookup) is
 * reported verbatim and thrown immediately: never retried, never worked around.
 */
async function fetchTweetBatch(ids: string[], token: string): Promise<TweetLookupResponse> {
  const url = `${X_API_URL}?ids=${ids.join(",")}&tweet.fields=${TWEET_FIELDS}&expansions=${EXPANSIONS}&user.fields=${USER_FIELDS}`;

  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    let response: Response;
    try {
      response = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });
    } catch (error) {
      if (attempt === MAX_RETRIES) throw new Error(`network error: ${(error as Error).message}`);
      await sleep(1000 * 2 ** attempt);
      continue;
    }

    if (response.ok) {
      return (await response.json()) as TweetLookupResponse;
    }

    const retryable = response.status === 429 || response.status >= 500;
    const bodyText = await response.text().catch(() => "");

    if (!retryable || attempt === MAX_RETRIES) {
      throw new FetchFailure(response.status, response.statusText, bodyText);
    }

    const resetHeader = response.headers.get("x-rate-limit-reset");
    const retryAfterHeader = response.headers.get("retry-after");
    let waitMs = 1000 * 2 ** attempt;
    if (resetHeader) {
      const resetAtMs = Number(resetHeader) * 1000;
      const untilReset = resetAtMs - Date.now();
      if (Number.isFinite(untilReset) && untilReset > 0) waitMs = Math.min(untilReset, 60_000);
    } else if (retryAfterHeader) {
      const seconds = Number(retryAfterHeader);
      if (Number.isFinite(seconds) && seconds > 0) waitMs = seconds * 1000;
    }
    console.error(
      `  fetch attempt ${attempt + 1} failed with HTTP ${response.status}; retrying in ${Math.round(waitMs / 1000)}s`,
    );
    await sleep(waitMs);
  }

  // Unreachable — the loop always returns or throws — but keeps TypeScript satisfied.
  throw new Error("fetchTweetBatch: exhausted retries without a terminal result");
}

class FetchFailure extends Error {
  constructor(
    public status: number,
    public statusText: string,
    public body: string,
  ) {
    super(`HTTP ${status} ${statusText}`);
  }
}

// ---------------------------------------------------------------------------
// Data loading / writing
// ---------------------------------------------------------------------------

function readDataFile<T>(fileName: string): T {
  return JSON.parse(readFileSync(resolve(DATA_DIR, fileName), "utf-8")) as T;
}

/** posts.json / amplifications.json currently ship with no trailing newline — preserved on write. */
function writeDataFile(fileName: string, data: unknown): void {
  writeFileSync(resolve(DATA_DIR, fileName), JSON.stringify(data, null, 2));
}

function backupDataFiles(): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupDir = resolve(CACHE_DIR, "backups", timestamp);
  mkdirSync(backupDir, { recursive: true });
  for (const fileName of ["posts.json", "amplifications.json"]) {
    writeFileSync(resolve(backupDir, fileName), readFileSync(resolve(DATA_DIR, fileName)));
  }
  return backupDir;
}

function writeCache(payload: unknown): void {
  mkdirSync(CACHE_DIR, { recursive: true });
  writeFileSync(CACHE_FILE, JSON.stringify(payload, null, 2));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const token = loadBearerToken();

  if (refreshMetrics) {
    // Still unimplemented — the refresh itself is docs/WORKPLAN.md B12. What
    // changed at B18 is that the contract it has to honour now exists, so
    // B12 has nothing left to invent: a refresh **appends** an observation to
    // `post.observations`, never replaces one, and the appended reading
    // carries `source: "api"` because that is where this script reads from.
    // The stored history must stay chronological and must not gain a second
    // reading for a date it already holds (docs/DATA.md §5).
    console.log(
      "--refresh-metrics was passed, but the refresh itself is not implemented yet " +
        "(docs/WORKPLAN.md B12). No observation will be appended. The contract it must " +
        'follow is in docs/DATA.md §5: append, never replace, with source "api".',
    );
  }

  // Loaded as raw JSON (not the zod-parsed/normalized shape) so untouched records are
  // written back byte-for-byte identical — schemas below are used only to *validate*,
  // never as the source of the object we persist (zod's nullish->null transforms would
  // otherwise inject keys real records currently omit, e.g. amplification follower_count).
  const posts = readDataFile<Post[]>("posts.json");
  const amplifications = readDataFile<Amplification[]>("amplifications.json");
  if (!postsFileSchema.safeParse(posts).success) {
    console.error("data/posts.json failed schema validation — run `pnpm validate:data` first. Aborting.");
    process.exit(1);
  }
  if (!amplificationsFileSchema.safeParse(amplifications).success) {
    console.error("data/amplifications.json failed schema validation — run `pnpm validate:data` first. Aborting.");
    process.exit(1);
  }

  const postIds = posts.map((post) => extractStatusId(post.url)).filter((id): id is string => id !== null);
  const ampIds = amplifications
    .map((amp) => extractStatusId(amp.evidence_url))
    .filter((id): id is string => id !== null);

  console.log(`Fetching ${postIds.length} post tweet(s) and ${ampIds.length} amplification evidence tweet(s)...`);

  let postsResponses: TweetLookupResponse[];
  let ampsResponses: TweetLookupResponse[];
  try {
    postsResponses = await Promise.all(chunk(postIds, 100).map((batch) => fetchTweetBatch(batch, token)));
    ampsResponses = await Promise.all(chunk(ampIds, 100).map((batch) => fetchTweetBatch(batch, token)));
  } catch (error) {
    if (error instanceof FetchFailure) {
      console.error(`\nX API request failed: HTTP ${error.status} ${error.statusText}`);
      console.error(`Response body: ${error.body}`);
      console.error(
        "\nThis is a likely outcome on the X API Free access tier, which does not permit tweet lookup " +
          "(GET /2/tweets). No retry loop, no workaround, and no invented content — data/*.json was not touched.",
      );
    } else {
      console.error(`\nEnrichment failed: ${(error as Error).message}`);
      console.error("data/*.json was not touched.");
    }
    process.exit(1);
  }

  writeCache({
    fetched_at: new Date().toISOString(),
    posts: postsResponses,
    amplifications: ampsResponses,
  });
  console.log(`Cached raw API responses to ${CACHE_FILE} (gitignored, never merged into canonical data).`);

  const tweetsById = new Map<string, ApiTweet>();
  const usersById = new Map<string, ApiUser>();
  const apiErrorsById = new Map<string, ApiError>();
  for (const response of [...postsResponses, ...ampsResponses]) {
    for (const tweet of response.data ?? []) tweetsById.set(tweet.id, tweet);
    for (const user of response.includes?.users ?? []) usersById.set(user.id, user);
    for (const err of response.errors ?? []) if (err.value) apiErrorsById.set(err.value, err);
  }

  const trackedStatusIdToPostId = new Map<string, string>();
  for (const post of posts) {
    const statusId = extractStatusId(post.url);
    if (statusId) trackedStatusIdToPostId.set(statusId, post.id);
  }

  // --- Posts ---------------------------------------------------------------

  const PENDING_NOTE = "Post content/title enrichment pending.";
  const updatedPosts: Post[] = [];
  const postReport: string[] = [];

  for (const post of posts) {
    const statusId = extractStatusId(post.url);
    if (!statusId) {
      postReport.push(`${post.id}: could not extract a tweet id from url — skipped.`);
      updatedPosts.push(post);
      continue;
    }

    const tweet = tweetsById.get(statusId);
    if (!tweet) {
      const apiError = apiErrorsById.get(statusId);
      postReport.push(
        `${post.id} (tweet ${statusId}): NOT RETURNED by API` +
          (apiError?.detail ? ` — ${apiError.detail}` : "") +
          ". Flagged for manual review; record left unchanged.",
      );
      updatedPosts.push(post);
      continue;
    }

    let next: Post = { ...post };
    const changes: string[] = [];

    // published_at — only corrected if the API contradicts the stored date.
    if (tweet.created_at) {
      const apiDate = tweet.created_at.slice(0, 10);
      if (apiDate !== next.published_at) {
        changes.push(`published_at: "${next.published_at}" -> "${apiDate}" (API created_at contradicts stored date)`);
        next = { ...next, published_at: apiDate };
      }
    }

    const enrichment = POST_ENRICHMENTS[post.id];
    if (enrichment) {
      changes.push(`title: "${next.title}" -> "${enrichment.title}"`);
      changes.push(`subject: ${JSON.stringify(next.subject)} -> ${JSON.stringify(enrichment.subject)}`);
      changes.push(`summary: ${JSON.stringify(next.summary)} -> ${JSON.stringify(enrichment.summary)}`);
      changes.push(`tags: ${JSON.stringify(next.tags)} -> ${JSON.stringify(enrichment.tags)}`);
      next = {
        ...next,
        title: enrichment.title,
        subject: enrichment.subject,
        summary: enrichment.summary,
        tags: enrichment.tags,
      };
      if (next.notes === PENDING_NOTE) {
        changes.push(`notes: ${JSON.stringify(next.notes)} -> null`);
        next = { ...next, notes: null };
      }
    } else if (post.notes === PENDING_NOTE) {
      const reason = FLAGGED_POSTS[post.id] ?? "No curated enrichment available for this post.";
      postReport.push(`${post.id} (tweet ${statusId}): FLAGGED FOR MANUAL REVIEW — ${reason}`);
    }

    if (changes.length > 0) {
      const validation = postSchema.safeParse(next);
      if (!validation.success) {
        postReport.push(
          `${post.id} (tweet ${statusId}): proposed changes FAILED validation, record left unchanged: ` +
            validation.error.issues.map((issue) => issue.message).join("; "),
        );
        updatedPosts.push(post);
        continue;
      }
      postReport.push(`${post.id} (tweet ${statusId}): OK — ${changes.join(" | ")}`);
      updatedPosts.push(next);
    } else {
      postReport.push(`${post.id} (tweet ${statusId}): confirmed, no changes needed.`);
      updatedPosts.push(post);
    }
  }

  // --- Amplifications --------------------------------------------------------

  const REFERENCED_TYPE_TO_ACTION: Record<ReferencedTweet["type"], Amplification["action"]> = {
    quoted: "quote_post",
    replied_to: "reply",
    retweeted: "repost",
  };

  const updatedAmplifications: Amplification[] = [];
  const ampReport: string[] = [];
  const promotionCandidates: string[] = [];

  for (const amp of amplifications) {
    const statusId = extractStatusId(amp.evidence_url);
    if (!statusId) {
      ampReport.push(`${amp.id}: could not extract a tweet id from evidence_url — skipped.`);
      updatedAmplifications.push(amp);
      continue;
    }

    const tweet = tweetsById.get(statusId);
    if (!tweet) {
      const apiError = apiErrorsById.get(statusId);
      ampReport.push(
        `${amp.id} (tweet ${statusId}): NOT RETURNED by API` +
          (apiError?.detail ? ` — ${apiError.detail}` : "") +
          ". Flagged for manual review; record left unchanged.",
      );
      updatedAmplifications.push(amp);
      continue;
    }

    let next: Amplification = { ...amp };
    const changes: string[] = [];
    const confirmations: string[] = [];

    // account / date confirmation (never auto-changed — only reported).
    const author = tweet.author_id ? usersById.get(tweet.author_id) : undefined;
    if (author) {
      const apiHandle = `@${author.username}`;
      if (amp.account && amp.account.toLowerCase() !== apiHandle.toLowerCase()) {
        ampReport.push(
          `${amp.id}: account mismatch — stored "${amp.account}", API says "${apiHandle}". Not auto-changed; flagged.`,
        );
      } else {
        confirmations.push(`account confirmed (${apiHandle})`);
      }
    }
    if (tweet.created_at) {
      const apiDate = tweet.created_at.slice(0, 10);
      if (apiDate !== amp.date) {
        ampReport.push(`${amp.id}: date mismatch — stored "${amp.date}", API says "${apiDate}". Not auto-changed; flagged.`);
      } else {
        confirmations.push("date confirmed");
      }
    }

    // action / related_post_id — derived directly from referenced_tweets.
    const firstReference = (tweet.referenced_tweets ?? []).find((ref) => ref.type in REFERENCED_TYPE_TO_ACTION);
    if (!firstReference) {
      ampReport.push(
        `${amp.id} (tweet ${statusId}): API returned no referenced_tweets — action/related_post_id not ` +
          `auto-confirmable from this evidence. Left as "${amp.action}"/${JSON.stringify(amp.related_post_id)}.`,
      );
    } else {
      const derivedAction = REFERENCED_TYPE_TO_ACTION[firstReference.type];
      const derivedRelatedPostId = trackedStatusIdToPostId.get(firstReference.id) ?? null;

      if (derivedAction !== amp.action) {
        changes.push(`action: "${amp.action}" -> "${derivedAction}" (API referenced_tweets: ${firstReference.type})`);
        next = { ...next, action: derivedAction };
      }
      if (derivedRelatedPostId !== amp.related_post_id) {
        changes.push(
          `related_post_id: ${JSON.stringify(amp.related_post_id)} -> ${JSON.stringify(derivedRelatedPostId)} ` +
            `(quoted/replied/retweeted tweet is ${firstReference.id}` +
            (derivedRelatedPostId ? `, a tracked post` : ", not a currently tracked post") +
            ")",
        );
        next = { ...next, related_post_id: derivedRelatedPostId };
      }

      if (changes.length === 0) {
        confirmations.push(`action and related_post_id confirmed (${derivedAction})`);
      } else {
        // Append the confirming evidence to the existing note rather than replacing it —
        // the prior investigatory note stays on record.
        const noteAddendum =
          `X API confirms: ${firstReference.type} of status ${firstReference.id}` +
          (derivedRelatedPostId ? ` (${derivedRelatedPostId}).` : " (not currently a tracked post).");
        next = { ...next, notes: amp.notes ? `${amp.notes} ${noteAddendum}` : noteAddendum };
        changes.push(`notes updated to record the confirmed evidence`);
      }
    }

    if (changes.length > 0) {
      const validation = amplificationSchema.safeParse(next);
      if (!validation.success) {
        ampReport.push(
          `${amp.id} (tweet ${statusId}): proposed changes FAILED validation, record left unchanged: ` +
            validation.error.issues.map((issue) => issue.message).join("; "),
        );
        updatedAmplifications.push(amp);
        continue;
      }
      ampReport.push(`${amp.id} (tweet ${statusId}): OK — ${changes.join(" | ")}`);
      updatedAmplifications.push(next);
      if (next.status === "needs_review") {
        promotionCandidates.push(
          `${amp.id}: now has evidence-confirmed action "${next.action}"` +
            (next.related_post_id ? ` linked to ${next.related_post_id}` : "") +
            " — status left as needs_review; promotion is the maintainer's decision.",
        );
      }
    } else {
      ampReport.push(`${amp.id} (tweet ${statusId}): ${confirmations.join(", ") || "confirmed, no changes needed."}`);
      updatedAmplifications.push(amp);
      if (amp.status === "needs_review" && firstReference) {
        promotionCandidates.push(
          `${amp.id}: action "${amp.action}" already matches confirmed API evidence` +
            (amp.related_post_id ? ` (linked to ${amp.related_post_id})` : "") +
            " — status left as needs_review; promotion is the maintainer's decision.",
        );
      }
    }
  }

  // --- Report ----------------------------------------------------------------

  console.log("\n=== Posts ===");
  for (const line of postReport) console.log(`  ${line}`);

  console.log("\n=== Amplifications ===");
  for (const line of ampReport) console.log(`  ${line}`);

  if (promotionCandidates.length > 0) {
    console.log("\n=== Promotion candidates (maintainer decision — not applied) ===");
    for (const line of promotionCandidates) console.log(`  ${line}`);
  }

  const postsChanged = JSON.stringify(posts) !== JSON.stringify(updatedPosts);
  const ampsChanged = JSON.stringify(amplifications) !== JSON.stringify(updatedAmplifications);

  if (isDryRun) {
    console.log(`\n--dry-run: no files written. posts changed: ${postsChanged}; amplifications changed: ${ampsChanged}.`);
    return;
  }

  if (!postsChanged && !ampsChanged) {
    console.log("\nNo changes to write.");
    return;
  }

  const backupDir = backupDataFiles();
  console.log(`\nBacked up data/posts.json and data/amplifications.json to ${backupDir}`);

  if (postsChanged) {
    writeDataFile("posts.json", updatedPosts);
    console.log("Wrote data/posts.json");
  }
  if (ampsChanged) {
    writeDataFile("amplifications.json", updatedAmplifications);
    console.log("Wrote data/amplifications.json");
  }
}

main().catch((error) => {
  console.error(`Unexpected error: ${(error as Error).message}`);
  process.exit(1);
});
